---
abstract: 'The customizations that turn a RT into a RT for rt.cpan.org'
author:
  - 'Thomas Sibley <trs@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-rt_cpan_org
no_index:
  directory:
    - etc
    - html
    - inc
requires:
  DBD::SQLite: 0
  DBI: 0
  File::Remove: 0
  File::Spec: 0
  Hook::LexWrap: 0
  IO::Compress::Gzip: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 4.0
