---
abstract: 'The customizations that turn a RT into a RT for rt.cpan.org'
author:
  - 'Thomas Sibley <trs@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-rt_cpan_org
no_index:
  directory:
    - html
    - inc
requires:
  Hook::LexWrap: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.03
